### ISSUE TITLE
Blows stack when deeply nested?

### ISSUE THREAD

**Issue by fasiha** [avinashcodes/callbag-flat-map#2]
Hi there, I've been using [`callbag-flatten`](https://github.com/staltz/callbag-flatten) manually to achieve what your library simplifies, but I noticed that using your library can cause Node to blow its stack whereas using `flatten` manually doesn't. I was able to simplify it to the following test case:

In a project where you've done `npm i tape callbag-basics callbag-flat-map callbag-flatten`, put this in a file and run it in Node:
```js
var { pipe, fromIter, map, forEach } = require('callbag-basics');
var flatten = require('callbag-flatten');
var flatMap = require('callbag-flat-map');
var tape = require('tape');

// Helper functions
function dumpbag(bag) {
  let ret = [];
  pipe(bag, forEach(x => ret.push(x)));
  return ret;
}
function cartesian(...args) {
  let bag = map(x => [x])(args[0]);
  for (let i = 1; i < args.length; i++) {
    bag = flatten(map(outer => pipe(args[i], map(inner => outer.concat(inner))))(bag))
  }
  return bag;
}
function cartesianArr(...args) { return cartesian(...args.map(arr => fromIter(arr))); }

var years = Array.from(Array(5), (_, i) => 2001 + i);
var URLS = 'abcdefghi'.split('');
var langs
    = 'aar,abk,ace,ach,ada,ady,afa,afh,afr,ain,aka,akk,alb,sqi,ale,alg,alt,amh,ang,anp,apa,ara,arc,arg,arm,hye,arn,arp,art,arw,asm,ast,ath,aus,ava,ave,awa,aym,aze,bad,bai,bak,bal,bam,ban,baq,eus,bas,bat,bej'
          .split(',');
function ls(url, year, lang) { return fromIter(Array.from(Array(5), (_, i) => `${url}${year}${lang}-${i}`)); }

// These two are the SAME callbags, but differently constructed (the second uses flatMap): both emit the cartesian
// product of {year, url, lang}.
var inputsCallbag = cartesianArr(years, URLS, langs);
var inputsCallbagNested
    = flatMap(yearUrl => fromIter(langs), ([ year, url ], lang) => [year, url, lang])(cartesianArr(years, URLS));

// Here's my version of a simplified flatMap that generalizes the example from callbag-flatten
var myflatmap
    = (splitter, combiner) => source => flatten(map(orig => map(next => combiner(orig, next))(splitter(orig)))(source));

// Here's the expected result, which I have verified
var expected = dumpbag(flatten(map(([ year, url, lang ]) => ls(url, year, lang))(inputsCallbag)));

var makeSource = ([ y, e, p ]) => ls(e, y, p);
var combiner = (_, res) => res;

tape("make sure both sources produce the same values", t => {
  t.deepEqual(dumpbag(inputsCallbag), dumpbag(inputsCallbagNested));
  t.end();
});

tape("manual, with nested source", t => {
  let actual = dumpbag(flatten(map(makeSource)(inputsCallbagNested)));
  t.deepEqual(actual, expected);
  t.end();
});

tape("myflatmap", t => {
  let actual = dumpbag(myflatmap(makeSource, combiner)(inputsCallbag));
  t.deepEqual(actual, expected);
  t.end();
});

tape("myflatmap, nested source", t => {
  let actual = dumpbag(myflatmap(makeSource, combiner)(inputsCallbagNested));
  t.deepEqual(actual, expected);
  t.end();
});

tape("callbag-flat-map", t => {
  let actual = dumpbag(flatMap(makeSource, combiner)(inputsCallbag));
  t.deepEqual(actual, expected);
  t.end();
});

// 💀💀💀 crashes with "RangeError: Maximum call stack size exceeded"
tape("callbag-flat-map, nested source 💀", t => {
  let actual = dumpbag(flatMap(makeSource, combiner)(inputsCallbagNested));
  t.deepEqual(actual, expected, 'callbag-flat-map with inputsCallbagNested');
  t.end();
});
```

Sorry for giving you such a long test case but I hope it'll be useful in debugging the problem. What this test does is, it sets up two sources, `inputsCallbag` and `inputsCallbagNested`, both of which produce the same values but the first is constructed using manual `callbag-flatten` while the second is constructed using `callbag-flat-map` (this repo). I test both of these sources on three implementations of `flatMap`:
- manually using `callbag-flatten` which is a bit confusing,
- your `callbag-flat-map`, and
- my generalization of `callbag-flatten`, called `myflatmap` above.

The test shows that all three work for the simpler `inputsCallbag` input, but `callbag-flat-map` fails with `RangeError: Maximum call stack size exceeded` when the second source `inputsCallbagNested` is evaluated using this repo. The other two implementations produce the expected answer.

```
$ node flat-test.js
TAP version 13
# make sure both sources produce the same values
ok 1 should be equivalent
# manual, with nested source
ok 2 should be equivalent
# myflatmap
ok 3 should be equivalent
# myflatmap, nested source
ok 4 should be equivalent
# callbag-flat-map
ok 5 should be equivalent
# callbag-flat-map, nested source 💀
/pathto/node_modules/callbag-flat-map/index.js:14
            else if (!sourceEnded) inputSourceTalkback(1);
                                   ^

RangeError: Maximum call stack size exceeded
    at pullHandle (/pathto/node_modules/callbag-flat-map/index.js:14:36)
    at pullHandle (/pathto/node_modules/callbag-flat-map/index.js:14:36)
    at pullHandle (/pathto/node_modules/callbag-flat-map/index.js:14:36)
    at pullHandle (/pathto/node_modules/callbag-flat-map/index.js:14:36)
    at pullHandle (/pathto/node_modules/callbag-flat-map/index.js:14:36)
    at pullHandle (/pathto/node_modules/callbag-flat-map/index.js:14:36)
    at pullHandle (/pathto/node_modules/callbag-flat-map/index.js:14:36)
    at pullHandle (/pathto/node_modules/callbag-flat-map/index.js:14:36)
    at pullHandle (/pathto/node_modules/callbag-flat-map/index.js:14:36)
    at pullHandle (/pathto/node_modules/callbag-flat-map/index.js:14:36)
```

I'm not sure if you want to try and debug why your implementation causes Node to recurse too deeply (see this [stackoverflow question about this](https://stackoverflow.com/questions/20936486/node-js-maximum-call-stack-size-exceeded#20999077)), or just use `myflatmap` as given above?

**Comment by alinz** [comment]
I had the similar issue and my friend @jaysoo give me a better code:

```
const flatMap = f => source => pipe(source, map(f), flatten)
```

**Comment by fasiha** [comment]
@alinz yeah, I made an alternative flatmap module based on that idea :) https://github.com/fasiha/callbag-flat-map-operator

**Comment by avinashcodes** [comment]
@fasiha  @alinz , Thanks for posting the detailed info 👍. I've been away from github for a long time. 
So there was a bug due to which stack is blowing up. Fixed it. 
As you might've already figured out, original `pipe(source, map(f), flatten)` would act as `switchMap` not `flatMap`. This package does flatten all the sources rather than switching as mentioned in the readme section.
